#+title: Detour library
#+options: toc:nil
#+startup: showeverything
#+export_file_name: ./doc/README.md
#+author: 8dcc

*Simple C library for detour hooking in linux.*

#+TOC: headlines 2

* Description

This is a linux library, but it should be easy to port to windows. As far as I
know, you should only need to change the [[https://github.com/8dcc/detour-lib/blob/f171e7fcb0e10eeb04c942c6f004a2fea75c7b2c/src/detour.c#L18-L30][protect_addr]] function.

It supports x64 and x86.

If you want to use this library, simply copy the detour source and headers to
your project, include the header in your source files and compile the detour
source with the rest of your code. Please see [[https://github.com/8dcc/detour-lib/blob/main/src/main.c][src/main.c]] and for an [[*Usage][Usage]]
example on how to use it.

This library was originally made for [[https://github.com/8dcc/hl-cheat][8dcc/hl-cheat]], and was inspired by
[[https://guidedhacking.com/threads/simple-linux-windows-detour-class.10580/][this OOP abomination]] ([[https://gist.github.com/8dcc/d0cbef32cd46ab9c73c6f830fa71d999][mirror]]).

* Building

#+begin_src console
$ git clone https://github.com/8dcc/detour-lib
$ cd detour-lib
$ make
...
#+end_src

* Usage

First, you will need to specify the type and arguments of the original function
with the =DETOUR_DECL_TYPE= macro. You will also need to declare a =detour_ctx_t=
context struct:

#+begin_src C
/* int orig(double a, double b); */
DETOUR_DECL_TYPE(int, orig, double, double);

detour_ctx_t detour_ctx;
#+end_src

This macro will =typedef= a type needed internally by the library, so make sure
you call it globally. The context struct be accesible when calling the original
function (e.g. from your hook), so keep that in mind as well.

Then, initialize the context struct by calling =detour_init= with a pointer to the
original function and a pointer to your hook function:

#+begin_src C
void* orig_ptr = &orig; /* orig(...) */
void* hook_ptr = &hook; /* hook(...) */

/* Initialize the detour context */
detour_init(&detour_ctx, orig_ptr, hook_ptr);

/* Hook the original function */
detour_add(&detour_ctx);
#+end_src

If you want to call the original function from your hook, you can use one of the
following macros:

- =DETOUR_ORIG_CALL=: Calls the original function, ignores the returned value.
- =DETOUR_ORIG_GET=: Takes an extra parameter used for storing the return value.

#+begin_src C
double hook(double a, double b) {
    /* Call original ignoring return */
    DETOUR_ORIG_CALL(&detour_ctx, orig, a, b);

    /* Store return value in variable */
    int result;
    DETOUR_ORIG_GET(&detour_ctx, result, orig, a, b);

    /* Our hook can overwrite the return value */
    return 123;
}
#+end_src

Once we are done, we can call =detour_del= to remove the hook:

#+begin_src C
/* Remove hook */
detour_del(&detour_ctx);
#+end_src

If we call =orig()= again, our hook function will not be called.

For a full working example, see [[https://github.com/8dcc/detour-lib/blob/main/src/main.c][src/main.c]]. You can also run =make all= or =make
all-32bit=, and try executing =detour-test.out=.
